### ISSUE TITLE
padding/margin

### ISSUE THREAD

**Issue by guer0125** [guer0125/modularity-mindfulness#2]
Hi,

I am having a lot of trouble adjusting my padding/margin to match the image enough to get the mark just for small screen, because i want to get the small screen to move on to the next ones. any tips?

I work and i find it hard to make time, that's why it seems so last minute but i've been working on it for a long time i just can't get the spaces right.

my margin are also somehow overlapping.

@hellachella

**Comment by guer0125** [comment]
hi, i fixed that. know im wonder how i can place each of my articles in the different columns.

**Comment by guer0125** [comment]
could you guide me in the right direction  to move rock garden and nav up?

thank you

**Comment by hellachella** [comment]
Taking a look

**Comment by hellachella** [comment]
1. Don't use ```<hr>```, use border-top and border-bottom in your css instead and apply padding.
2. Move your banner image out of the header and into the ```<main>``` just above the  ```<section>```
3. The hierarchy should be as such:
```<body>
  
  <header> <!-- display flex -->
    <h1> <!-- treat this <h1> as a container, use display flex and flex direction to stack them -->
      <i><!--content in ja--></i><!-- content in en -->
    </h1>
    <nav>
      <ul> <!-- display flex -->
        <li></li>
        <li></li>
        <li></li>
      </ul>
    </nav>
  </header>

  <main>
    <img src="" alt=""> <!-- banner image --->
    <div class="">
      <!-- Intro info etc -->
    </div>

    <section> <!-- display grid -->
      <article class="">
        <!-- figure -->
      </article>

      <article class="">
        <!-- figure -->
      </article>

      <article class="">
        <!-- figure -->
      </article>
    </section>

  </main>

  <footer>
    <!-- content -->
  </footer>
</body>
```

**Comment by guer0125** [comment]
if i have both the japanese and english title in H1..how can i make one bigger than the other?, in markbot the japanese is bigger than english. so i have make english font size smalles

**Comment by hellachella** [comment]
Use a `span` around the english text.

**Comment by guer0125** [comment]
how can i move my nav to the right? using flex
